#extend:
app_name: "efa"

evernote:
  api_token: __FIX_ME__
  sandbox: False
  notebooks:
    -


logging:
  log_dir: ${join(ROOT, "log")}
  log_filename: ${app_name+".log"}
  log_file: ${join(logging.log_dir, logging.log_filename)}
  format: "%(asctime)s %(levelname)s: %(message)s"
  level: 30
          #CRITICAL = 50
          #FATAL = CRITICAL
          #ERROR = 40
          #WARNING = 30
          #WARN = WARNING
          #INFO = 20
          #DEBUG = 10
          #NOTSET = 0

font_size: 20
line_height: 150
